<?php

namespace Tests\Listeners;

use Illuminate\Queue\Events\JobFailed;
use Tests\TestCase;
use App\Listeners\JobFailedEventListener;

class JobFailedEventListenerTest extends TestCase
{
    public function testHandle()
    {
        $client = \Mockery::mock('Aws\CloudWatch\CloudWatchClient')
            ->shouldReceive('putMetricData')
            ->andReturn([])
            ->once()
            ->getMock();

        $listener = new JobFailedEventListener($client);
        $listener->handle(new JobFailed('does', 'not', 'matter'));
    }

    public function tearDown()
    {
        if ($container = \Mockery::getContainer()) {
            $this->addToAssertionCount($container->mockery_getExpectationCount());
        }
        \Mockery::close();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
